Jj profile page
jessjno/photogram-industrial pull request #4
Opened 2024-10-15 21:16 UTC by jessjno

created the username route, set up the show action, added photos under the users and photo commenting

2024-10-16 16:06 UTC, marywebby requested changes
Looking good! You're off to a great start but make sure you go through and make the changes in the places where I have linked back to the lesson. Once you have made those reassign me as a reviewer and I can approve it!

2024-10-16 16:06 UTC, marywebby commented on app/controllers/comments_controller.rb
> +        format.html { redirect_to fallback_location: root_path, notice: "Comment was successfully created." }
good job implementing the fallback_location, but make sure you are using the correct `redirect` in this situation, double check the lesson at this part [here](https://learn.firstdraft.com/run/84-software-development-foundations-dpi/courses/98-software-development-foundations-dpi/lessons/200-photogram-industrial-part-4#:~:text=seen%20yet%20called-,redirect_back,-%3A)

2024-10-16 16:06 UTC, marywebby commented on app/controllers/users_controller.rb
looking good!!

2024-10-16 16:06 UTC, marywebby commented on app/views/comments/_form.html.erb
>    <div>
just a little nitpick, but make sure to add the bootstrap inline styling to this div! `class="mb-3"

2024-10-16 16:06 UTC, marywebby commented on app/views/users/show.html.erb
> +                  <img src="..." alt="...">
scr and alt are empty, no biggie at the moment, but could be good to place something like `commenter's avatar` or a `placeholder image` in there just for now.

2024-10-16 16:06 UTC, marywebby commented on config/routes.rb
>    devise_for :users
nice job implementing devise! Apologies what you have is correct.

2024-10-16 16:34 UTC, Testell approved these changes
looks good!

2024-10-16 17:28 UTC, marywebby approved these changes
Looks good!!! Thank you for making those changes

2024-10-16 20:44 UTC, merged

2024-10-18 15:34 UTC, dgarcia13-99 commented
looks good! You did a great job of formatting your files, so everything is nicely indented! Good job making recommended edits!

2024-10-18 16:33 UTC, dgarcia13-99 reviewed
looks good! You did a great job formatting your files, so everything is nicely indented! Good job making recommended edits!

2024-10-18 20:07 UTC, viviancreates reviewed
Great job refactoring the comment form! Looks like you made some good edits