Jj tabbed interface
jessjno/photogram-industrial pull request #5
Opened 2024-10-16 23:28 UTC by jessjno

added user liked photos and user photos links to user profile

2024-10-17 16:05 UTC, armstrca requested changes

2024-10-17 16:05 UTC, armstrca commented on app/views/photos/_photo.html.erb
> +          <li class="list-group-item">
The bullet points next to each comment are rendering outside the parent box - they should be inside

2024-10-17 17:06 UTC, armstrca commented on app/views/users/show.html.erb
> +  <div class="col md-6 offset-3">
Should be `col-md-6`

2024-10-17 17:06 UTC, armstrca commented on app/views/users/liked.html.erb
> +  <div class="col md-6 offset-3">
should be `col-md-6`

2024-10-17 17:09 UTC, Testell approved these changes
Resolved styling looks great!

2024-10-17 18:31 UTC, armstrca approved these changes

2024-10-17 19:21 UTC, merged

2024-10-18 15:37 UTC, dgarcia13-99 commented
You did a great job formatting the tabbed interface cards, and your styling looks great after the edits!

2024-10-18 16:32 UTC, dgarcia13-99 reviewed
Great job making the appropriate changes!